name: learn-github-actions
run-name: ${{ github.actor }} is learning-github-actions
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latets
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run test

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latets
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and pushDocker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 2106144/coba-action:latest